# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fixed.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 735)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: #6F4E37; /* Màu cà phê */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D4037; /* Đậm hơn khi di chuột */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 5, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 2, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #F5F5DC; /* Màu kem */\n"
"    border-radius: 20px;\n"
"    border: 1px solid #D2B48C;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/16edaf03-df12-4f77-90d0-a4496ceb8155.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:/pngtree-a-cup-of-mocha-coffee-with-heart-latte-art-on-top-image_15671868.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(30, -1, 30, -1)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setMinimumSize(QtCore.QSize(0, 40))
        self.password.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #4E342E;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6F4E37; /* Đổi màu viền khi click vào */\n"
"}")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 0, 1, 1)
        self.user_name = QtWidgets.QLineEdit(self.frame)
        self.user_name.setMinimumSize(QtCore.QSize(0, 40))
        self.user_name.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #4E342E;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6F4E37; /* Đổi màu viền khi click vào */\n"
"}")
        self.user_name.setObjectName("user_name")
        self.gridLayout.addWidget(self.user_name, 0, 0, 1, 1)
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setMinimumSize(QtCore.QSize(0, 40))
        self.b1.setStyleSheet("QPushButton {\n"
"    background-color: #4E342E;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    min-height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #6F4E37;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3E2723;\n"
"}")
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 3, 0, 1, 1)
        self.b2 = QtWidgets.QPushButton(self.frame)
        self.b2.setMinimumSize(QtCore.QSize(10, 40))
        self.b2.setStyleSheet("QPushButton {\n"
"    background-color: #4E342E;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    min-height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #6F4E37;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3E2723;\n"
"}")
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.frame, 2, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login - Coffee App"))
        self.password.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.user_name.setPlaceholderText(_translate("MainWindow", "Enter username"))
        self.b1.setText(_translate("MainWindow", "Sign in"))
        self.b2.setText(_translate("MainWindow", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
