# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lichsuhoadon.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 1340)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: #5a2d0c;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7a3f14;\n"
"}\n"
"QFrame#sidebar {\n"
"    background-color: #e8d3b3;\n"
"}\n"
"QFrame#main_area {\n"
"    background-color: #f5e6cc;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(self.sidebar)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("D:/16edaf03-df12-4f77-90d0-a4496ceb8155.jpg"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.btn_ban = QtWidgets.QPushButton(self.sidebar)
        self.btn_ban.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_ban.setFont(font)
        self.btn_ban.setObjectName("btn_ban")
        self.verticalLayout.addWidget(self.btn_ban)
        self.btn_hd = QtWidgets.QPushButton(self.sidebar)
        self.btn_hd.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_hd.setFont(font)
        self.btn_hd.setObjectName("btn_hd")
        self.verticalLayout.addWidget(self.btn_hd)
        self.btn_tk = QtWidgets.QPushButton(self.sidebar)
        self.btn_tk.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_tk.setFont(font)
        self.btn_tk.setObjectName("btn_tk")
        self.verticalLayout.addWidget(self.btn_tk)
        self.btn_logout = QtWidgets.QPushButton(self.sidebar)
        self.btn_logout.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout.addWidget(self.btn_logout)
        self.hboxlayout.addWidget(self.sidebar)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName("frame")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.frame)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.search_input = QtWidgets.QLineEdit(self.frame)
        self.search_input.setObjectName("search_input")
        self.hboxlayout1.addWidget(self.search_input)
        self.btn_search = QtWidgets.QPushButton(self.frame)
        self.btn_search.setObjectName("btn_search")
        self.hboxlayout1.addWidget(self.btn_search)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.table_history = QtWidgets.QTableWidget(self.frame)
        self.table_history.setObjectName("table_history")
        self.table_history.setColumnCount(4)
        self.table_history.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history.setHorizontalHeaderItem(3, item)
        self.vboxlayout.addWidget(self.table_history)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.btn_view = QtWidgets.QPushButton(self.frame)
        self.btn_view.setObjectName("btn_view")
        self.hboxlayout2.addWidget(self.btn_view)
        self.btn_delete = QtWidgets.QPushButton(self.frame)
        self.btn_delete.setObjectName("btn_delete")
        self.hboxlayout2.addWidget(self.btn_delete)
        self.vboxlayout.addLayout(self.hboxlayout2)
        self.hboxlayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lịch sử hóa đơn"))
        self.btn_ban.setText(_translate("MainWindow", "Danh sách bàn"))
        self.btn_hd.setText(_translate("MainWindow", "Hóa đơn"))
        self.btn_tk.setText(_translate("MainWindow", "Thống kê"))
        self.btn_logout.setText(_translate("MainWindow", "Đăng xuất"))
        self.label.setStyleSheet(_translate("MainWindow", "font-size:20px; font-weight:bold;"))
        self.label.setText(_translate("MainWindow", "LỊCH SỬ HÓA ĐƠN"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Tìm theo ngày hoặc mã hóa đơn..."))
        self.btn_search.setText(_translate("MainWindow", "Tìm"))
        item = self.table_history.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã HĐ"))
        item = self.table_history.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Thời gian"))
        item = self.table_history.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Số món"))
        item = self.table_history.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tổng tiền"))
        self.btn_view.setText(_translate("MainWindow", "Xem chi tiết"))
        self.btn_delete.setText(_translate("MainWindow", "Xóa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
