# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 412)
        MainWindow.setMinimumSize(QtCore.QSize(0, 3))
        MainWindow.setMaximumSize(QtCore.QSize(16777212, 16777215))
        MainWindow.setStyleSheet("/* Bo góc và làm mịn ô nhập liệu */\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    background: white;\n"
"}\n"
"/* Đổi màu viền khi click vào ô */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #795548;\n"
"}\n"
"\n"
"/* Làm nút Sign in chuyên nghiệp */\n"
"QPushButton {\n"
"    background-color: #795548;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    min-height: 40px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D4037;\n"
"}\n"
"\n"
"/* Nút Sign up dạng link xanh */\n"
"#label_signup, QPushButton#pushButton_signup {\n"
"    color: #007bff;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"/* Tiêu đề */\n"
"QLabel#label_title {\n"
"    font-size: 20px;\n"
"    color: #4E342E;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Các ô nhập liệu to và đẹp */\n"
"QLineEdit {\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    min-height: 35px; /* Làm ô to ra */\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"/* Nút Sign in chính */\n"
"QPushButton#btn_login { \n"
"    background-color: #795548;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    min-height: 40px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Nút Sign up nhỏ phía dưới */\n"
"#btn_signup {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #5D4037;\n"
"    font-size: 12px;\n"
"    text-decoration: underline;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(80, -1, 80, 1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.user_name = QtWidgets.QLineEdit(self.centralwidget)
        self.user_name.setMinimumSize(QtCore.QSize(53, 53))
        self.user_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.user_name.setObjectName("user_name")
        self.verticalLayout.addWidget(self.user_name)
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setMinimumSize(QtCore.QSize(53, 53))
        self.password.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setStyleSheet("QPushButton {\n"
"    border: none;             /* Xóa khung nút */\n"
"    background: transparent;  /* Nền trong suốt */\n"
"    color: blue;              /* Màu chữ xanh giống link */\n"
"    text-decoration: underline; /* Gạch chân */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: red;               /* Đổi sang màu đỏ khi di chuột vào */\n"
"}\n"
"background: transparent; border: none; color: blue; font-size: 11px; text-align: right;")
        self.b2.setObjectName("b2")
        self.verticalLayout.addWidget(self.b2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TAO\'S Coffee & Tea"))
        self.user_name.setPlaceholderText(_translate("MainWindow", "Enter Username"))
        self.password.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.login.setText(_translate("MainWindow", "Sign in"))
        self.b2.setText(_translate("MainWindow", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
