# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import sqlite3
from PyQt5 import QtWidgets, uic, QtCore,QtGui

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Đường dẫn database
DB_FOLDER = os.path.join(BASE_DIR, "database")
os.makedirs(DB_FOLDER, exist_ok=True)
DB_PATH = os.path.join(DB_FOLDER, "shop_data.db")


class LoginWindow(QtWidgets.QMainWindow):
    def __init__(self, parent_widget):
        super().__init__()
        self.widget = parent_widget
        
        # Load giao diện
        uic.loadUi(os.path.join(BASE_DIR, 'view', 'login.ui'), self)
        
        # Xóa ảnh mặc định nếu có
        if hasattr(self, 'label'):
            self.label.clear()
        
        # Kết nối nút
        self.b1.clicked.connect(self.login)
        self.b2.clicked.connect(self.go_to_signup)

    def go_to_signup(self):
        self.widget.setCurrentIndex(1)  # Chuyển sang Signup

    def login(self):
        username = self.name.text().strip()
        password = self.password.text().strip()
        
        if not username or not password:
            self.error.setText("Vui lòng nhập đầy đủ!")
            return

        conn = sqlite3.connect(DB_PATH)
        cur = conn.cursor()
        cur.execute("SELECT password FROM login_info WHERE username = ?", (username,))
        result = cur.fetchone()
        conn.close()

        if result is None:
            self.error.setText("Tài khoản không tồn tại!")
        elif result[0] == password:
            self.error.setText("✅ Đăng nhập thành công!")
            # ==================== CHỈNH SỬA Ở ĐÂY ====================
            self.widget.setCurrentIndex(2)   # Chuyển sang DSWindow (Danh sách bàn)
            # Không chuyển thẳng sang Menu nữa
        else:
            self.error.setText("❌ Sai mật khẩu!")



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 1225)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: #6F4E37; /* Màu cà phê */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5D4037; /* Đậm hơn khi di chuột */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 5, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 2, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #F5F5DC; /* Màu kem */\n"
"    border-radius: 20px;\n"
"    border: 1px solid #D2B48C;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/16edaf03-df12-4f77-90d0-a4496ceb8155.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(30, -1, 30, -1)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.b2 = QtWidgets.QPushButton(self.frame)
        self.b2.setMinimumSize(QtCore.QSize(10, 60))
        self.b2.setStyleSheet("QPushButton {\n"
"    background-color: #4E342E;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    min-height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #6F4E37;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3E2723;\n"
"}")
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 5, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setMinimumSize(QtCore.QSize(0, 40))
        self.password.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #4E342E;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6F4E37; /* Đổi màu viền khi click vào */\n"
"}")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 0, 1, 1)
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setMinimumSize(QtCore.QSize(0, 60))
        self.b1.setStyleSheet("QPushButton {\n"
"    background-color: #4E342E;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    min-height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #6F4E37;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3E2723;\n"
"}")
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 4, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.frame)
        self.name.setMinimumSize(QtCore.QSize(0, 40))
        self.name.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #4E342E;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6F4E37; /* Đổi màu viền khi click vào */\n"
"}")
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 0, 1, 1)
        self.error = QtWidgets.QLabel(self.frame)
        self.error.setText("")
        self.error.setObjectName("error")
        self.gridLayout.addWidget(self.error, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.frame, 2, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login - Coffee App"))
        self.b2.setText(_translate("MainWindow", "Sign Up"))
        self.password.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.b1.setText(_translate("MainWindow", "Sign in"))
        self.name.setPlaceholderText(_translate("MainWindow", "Enter username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
