# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taomoi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1188, 838)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: #795548; /* Màu nâu cafe đồng bộ */\n"
"    color: white;\n"
"    border-radius: 20px;       /* Bo tròn hai đầu cho \"dẹp\" và sang */\n"
"    min-height: 40px;\n"
"    font-weight: bold;\n"
"    margin-top: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5D4037;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 15px;      /* Bo tròn ô nhập liệu */\n"
"    padding: 5px 15px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #F5F5DC; /* Màu kem */\n"
"    border-radius: 20px;\n"
"    border: 1px solid #D2B48C;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/16edaf03-df12-4f77-90d0-a4496ceb8155.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(30, -1, 30, -1)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.b3 = QtWidgets.QPushButton(self.frame)
        self.b3.setMinimumSize(QtCore.QSize(10, 55))
        self.b3.setStyleSheet("QPushButton {\n"
"    background-color: #4E342E;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    min-height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #6F4E37;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3E2723;\n"
"}")
        self.b3.setObjectName("b3")
        self.gridLayout.addWidget(self.b3, 4, 0, 1, 1)
        self.nw_name = QtWidgets.QLineEdit(self.frame)
        self.nw_name.setMinimumSize(QtCore.QSize(0, 40))
        self.nw_name.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #4E342E;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6F4E37; /* Đổi màu viền khi click vào */\n"
"}")
        self.nw_name.setObjectName("nw_name")
        self.gridLayout.addWidget(self.nw_name, 2, 0, 1, 1)
        self.last_name = QtWidgets.QLineEdit(self.frame)
        self.last_name.setMinimumSize(QtCore.QSize(0, 40))
        self.last_name.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #4E342E;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6F4E37; /* Đổi màu viền khi click vào */\n"
"}")
        self.last_name.setObjectName("last_name")
        self.gridLayout.addWidget(self.last_name, 1, 0, 1, 1)
        self.nw_pass = QtWidgets.QLineEdit(self.frame)
        self.nw_pass.setMinimumSize(QtCore.QSize(0, 40))
        self.nw_pass.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #4E342E;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6F4E37; /* Đổi màu viền khi click vào */\n"
"}")
        self.nw_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.nw_pass.setObjectName("nw_pass")
        self.gridLayout.addWidget(self.nw_pass, 3, 0, 1, 1)
        self.first_name = QtWidgets.QLineEdit(self.frame)
        self.first_name.setMinimumSize(QtCore.QSize(0, 40))
        self.first_name.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #4E342E;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #6F4E37; /* Đổi màu viền khi click vào */\n"
"}")
        self.first_name.setObjectName("first_name")
        self.gridLayout.addWidget(self.first_name, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.frame, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1188, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b3.setText(_translate("MainWindow", "Sign Up"))
        self.nw_name.setPlaceholderText(_translate("MainWindow", "Enter username"))
        self.last_name.setPlaceholderText(_translate("MainWindow", "Enter your last name"))
        self.nw_pass.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.first_name.setPlaceholderText(_translate("MainWindow", "Enter your first name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
