# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taomoi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 438)
        MainWindow.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    background: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #795548;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    min-height: 40px;\n"
"    font-weight: bold;\n"
"    margin-top: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5D4037;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    color: #444;\n"
"}\n"
"QPushButton {\n"
"    text-align: center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(40, -1, 40, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.ho = QtWidgets.QLineEdit(self.centralwidget)
        self.ho.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ho.setObjectName("ho")
        self.verticalLayout.addWidget(self.ho)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.ten = QtWidgets.QLineEdit(self.centralwidget)
        self.ten.setMaximumSize(QtCore.QSize(500, 16777215))
        self.ten.setObjectName("ten")
        self.verticalLayout.addWidget(self.ten)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dn_m = QtWidgets.QLineEdit(self.centralwidget)
        self.dn_m.setMaximumSize(QtCore.QSize(500, 16777215))
        self.dn_m.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"}")
        self.dn_m.setObjectName("dn_m")
        self.verticalLayout.addWidget(self.dn_m)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.mk_m = QtWidgets.QLineEdit(self.centralwidget)
        self.mk_m.setMaximumSize(QtCore.QSize(500, 16777215))
        self.mk_m.setObjectName("mk_m")
        self.verticalLayout.addWidget(self.mk_m)
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.b3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.b3.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"}")
        self.b3.setIconSize(QtCore.QSize(0, 0))
        self.b3.setAutoRepeatDelay(0)
        self.b3.setObjectName("b3")
        self.verticalLayout.addWidget(self.b3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 345, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "TAO\'S Coffee & Tea"))
        self.label_3.setText(_translate("MainWindow", "First name"))
        self.label_4.setText(_translate("MainWindow", "Last name"))
        self.label.setText(_translate("MainWindow", "User name"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.b3.setText(_translate("MainWindow", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
