# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thongke.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
import os
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, "database", "shop_data.db")
class CotWindow(QtWidgets.QMainWindow):
    def __init__(self, parent_widget=None):
        super().__init__()
        self.widget = parent_widget

        ui_path = os.path.join(BASE_DIR, 'view', 'thongke.ui')
        uic.loadUi(ui_path, self)
        # connect button
        self.btn_ban_2.clicked.connect(self.open_ds_ban)
        self.btn_ban.clicked.connect(self.open_hoadon)
        #self.btn_them_mon.clicked.connect(self.open_them_mon)
        self.setup_chart() # 🔥 tạo timer self.timer = QtCore.QTimer()
        # 🔥 tạo timer
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_chart)
        self.timer.start(5000)  # 5 giây

        # filter
        self.combo_filter.currentIndexChanged.connect(self.update_chart)

        # chạy lần đầu
        self.update_chart()
    def open_ds_ban(self):
        self.widget.setCurrentIndex(2)

    def open_hoadon(self):
        self.widget.setCurrentIndex(4)

    def update_chart(self):
        mode = self.combo_filter.currentText()

        if mode == "7 ngày":
            days, revenue = self.get_daily_revenue(7)

        elif mode == "30 ngày":
            days, revenue = self.get_daily_revenue(30)

        elif mode == "Theo tháng":
            days, revenue = self.get_monthly_revenue()

        else:  # nếu bạn thêm "Theo năm"
            days, revenue = self.get_yearly_revenue()

        self.plot_chart(days, revenue)
    def get_daily_revenue(self, num_days):
        import sqlite3

        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()

        cursor.execute(f"""
            SELECT 
                substr(order_time, 1, 10) as day,
                SUM(total)
            FROM orders_history
            GROUP BY day
            ORDER BY day DESC
            LIMIT {num_days}
        """)

        data = cursor.fetchall()
        conn.close()

        data.reverse()

        days = [row[0] for row in data]
        revenue = [row[1] for row in data]

        return days, revenue
    def get_monthly_revenue(self):
        import sqlite3

        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()

        cursor.execute("""
            SELECT 
                substr(order_time, 4, 7) as month,  -- mm/YYYY
                SUM(total)
            FROM orders_history
            GROUP BY month
            ORDER BY month
        """)

        data = cursor.fetchall()
        conn.close()

        months = [f"T{int(row[0][:2])}" for row in data]
        revenue = [row[1] for row in data]

        return months, revenue
    def get_yearly_revenue(self):
        import sqlite3

        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()

        cursor.execute("""
            SELECT 
                substr(order_time, 7, 4) as year,
                SUM(total)
            FROM orders_history
            GROUP BY year
            ORDER BY year
        """)

        data = cursor.fetchall()
        conn.close()

        years = [row[0] for row in data]
        revenue = [row[1] for row in data]

        return years, revenue
    def plot_chart(self, labels, revenue):
        from matplotlib.ticker import FuncFormatter

        self.figure.clear()
        ax = self.figure.add_subplot(111)

        ax.bar(labels, revenue, width=0.6, color="#6b3e26")

        ax.set_title("Biểu đồ doanh thu", fontsize=14)
        ax.set_xlabel("Thời gian")
        ax.set_ylabel("VNĐ")

        # 🔥 format tiền VNĐ
        def format_money(x, pos):
            return f"{int(x):,}"

        ax.yaxis.set_major_formatter(FuncFormatter(format_money))

        ax.grid(axis='y', linestyle='--', alpha=0.7)
        # Sau khi vẽ biểu đồ cột
        bars = ax.patches  # lấy danh sách các thanh vừa vẽ

        # Tìm giá trị lớn nhất để canh khoảng cách cho số
        max_height = max(revenue) if revenue else 0
        offset = max_height * 0.03  # 3% chiều cao cột lớn nhất

        for bar, value in zip(bars, revenue):
            height = bar.get_height()
            # Định dạng số có dấu phẩy ngăn cách hàng nghìn
            label = f"{value:,.0f} đ"
            ax.text(
                bar.get_x() + bar.get_width() / 2,   # tọa độ x: giữa thanh
                height + offset,                     # tọa độ y: phía trên thanh 1 khoảng
                label,
                ha='center', va='bottom', fontsize=9, color='black'
            )
        # Mở rộng trục Y
        ylim = ax.get_ylim()
        ax.set_ylim(0, ylim[1] + offset * 2)
        self.canvas.draw()

        total = sum(revenue)
        self.total_label.setText(f"Tổng: {total:,} đ")
    def setup_chart(self):
        self.figure = Figure()
        self.canvas = FigureCanvas(self.figure)

        layout = QtWidgets.QVBoxLayout()

        # 🔥 clear layout cũ nếu có
        if self.chart_widget.layout() is not None:
            QtWidgets.QWidget().setLayout(self.chart_widget.layout())

        layout.addWidget(self.canvas)
        self.chart_widget.setLayout(layout)
class Ui_RevenueWindow(object):
    def setupUi(self, RevenueWindow):
        RevenueWindow.setObjectName("RevenueWindow")
        RevenueWindow.resize(961, 1380)
        RevenueWindow.setStyleSheet("""
QPushButton {
    background-color: #5a2d0c;
    color: white;
    border-radius: 10px;
    padding: 10px;
}
QPushButton:hover {
    background-color: #7a3f14;
}

/* sidebar */
QFrame#sidebar_2 {
    background-color: #f5e6cc;
}

/* main */
QFrame#main_area {
    background-color: #f5e6cc;
}

/* 🔥 QUAN TRỌNG: tất cả widget con */
QWidget {
    background-color: #f5e6cc;
}
""")
        self.centralwidget = QtWidgets.QWidget(RevenueWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_2 = QtWidgets.QFrame(self.centralwidget)
        self.sidebar_2.setObjectName("sidebar_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_2 = QtWidgets.QLabel(self.sidebar_2)
        self.logo_2.setText("")
        self.logo_2.setPixmap(QtGui.QPixmap("D:/16edaf03-df12-4f77-90d0-a4496ceb8155.jpg"))
        self.logo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_2.setObjectName("logo_2")
        self.verticalLayout_2.addWidget(self.logo_2)
        self.btn_ban_2 = QtWidgets.QPushButton(self.sidebar_2)
        self.btn_ban_2.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_ban_2.setFont(font)
        self.btn_ban_2.setObjectName("btn_ban_2")
        self.verticalLayout_2.addWidget(self.btn_ban_2)
        self.btn_ban = QtWidgets.QPushButton(self.sidebar_2)
        self.btn_ban.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_ban.setFont(font)
        self.btn_ban.setObjectName("btn_ban")
        self.verticalLayout_2.addWidget(self.btn_ban)
        self.btn_tk = QtWidgets.QPushButton(self.sidebar_2)
        self.btn_tk.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_tk.setFont(font)
        self.btn_tk.setObjectName("btn_tk")
        self.verticalLayout_2.addWidget(self.btn_tk)
        self.btn_them_mon = QtWidgets.QPushButton(self.sidebar_2)
        self.btn_them_mon.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_them_mon.setFont(font)
        self.btn_them_mon.setObjectName("btn_them_mon")
        self.verticalLayout_2.addWidget(self.btn_them_mon)
        self.horizontalLayout.addWidget(self.sidebar_2)
        self.main_area = QtWidgets.QFrame(self.centralwidget)
        self.main_area.setObjectName("main_area")
        self.mainLayout = QtWidgets.QVBoxLayout(self.main_area)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.title = QtWidgets.QLabel(self.main_area)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.headerLayout.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.combo_filter = QtWidgets.QComboBox(self.main_area)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_filter.setFont(font)
        self.combo_filter.setObjectName("combo_filter")
        self.combo_filter.addItem("")
        self.combo_filter.addItem("")
        self.combo_filter.addItem("")
        self.headerLayout.addWidget(self.combo_filter)
        self.mainLayout.addLayout(self.headerLayout)
        self.total_label = QtWidgets.QLabel(self.main_area)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.total_label.setFont(font)
        self.total_label.setObjectName("total_label")
        self.mainLayout.addWidget(self.total_label)
        self.chart_widget = QtWidgets.QWidget(self.main_area)
        self.chart_widget.setObjectName("chart_widget")
        self.mainLayout.addWidget(self.chart_widget)
        self.mainLayout.setStretch(2, 2)
        self.horizontalLayout.addWidget(self.main_area)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        RevenueWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RevenueWindow)
        QtCore.QMetaObject.connectSlotsByName(RevenueWindow)

    def retranslateUi(self, RevenueWindow):
        _translate = QtCore.QCoreApplication.translate
        RevenueWindow.setWindowTitle(_translate("RevenueWindow", "Thống kê doanh thu"))
        self.btn_ban_2.setText(_translate("RevenueWindow", "Danh sách bàn"))
        self.btn_ban.setText(_translate("RevenueWindow", "Hóa đơn"))
        self.btn_tk.setText(_translate("RevenueWindow", "Thống kê"))
        self.btn_them_mon.setText(_translate("RevenueWindow", "Thêm món"))
        self.title.setText(_translate("RevenueWindow", "Thống kê doanh thu"))
        self.combo_filter.setItemText(0, _translate("RevenueWindow", "7 ngày"))
        self.combo_filter.setItemText(1, _translate("RevenueWindow", "30 ngày"))
        self.combo_filter.setItemText(2, _translate("RevenueWindow", "Theo tháng"))
        self.total_label.setText(_translate("RevenueWindow", "Tổng: 0 đ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RevenueWindow = QtWidgets.QMainWindow()
    ui = Ui_RevenueWindow()
    ui.setupUi(RevenueWindow)
    RevenueWindow.show()
    sys.exit(app.exec_())
