# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thongke.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: #5a2d0c;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7a3f14;\n"
"}\n"
"QFrame#sidebar {\n"
"    background-color: #e8d3b3;\n"
"}\n"
"QFrame#main_area {\n"
"    background-color: #f5e6cc;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setMinimumSize(QtCore.QSize(0, 300))
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(self.sidebar)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("D:/16edaf03-df12-4f77-90d0-a4496ceb8155.jpg"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.btn_ban = QtWidgets.QPushButton(self.sidebar)
        self.btn_ban.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_ban.setFont(font)
        self.btn_ban.setObjectName("btn_ban")
        self.verticalLayout.addWidget(self.btn_ban)
        self.btn_hd = QtWidgets.QPushButton(self.sidebar)
        self.btn_hd.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_hd.setFont(font)
        self.btn_hd.setObjectName("btn_hd")
        self.verticalLayout.addWidget(self.btn_hd)
        self.btn_tk = QtWidgets.QPushButton(self.sidebar)
        self.btn_tk.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_tk.setFont(font)
        self.btn_tk.setObjectName("btn_tk")
        self.verticalLayout.addWidget(self.btn_tk)
        self.btn_logout = QtWidgets.QPushButton(self.sidebar)
        self.btn_logout.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout.addWidget(self.btn_logout)
        self.horizontalLayout.addWidget(self.sidebar)
        self.frame_right = QtWidgets.QFrame(self.centralwidget)
        self.frame_right.setObjectName("frame_right")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.frame_right)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.frame_orders = QtWidgets.QFrame(self.frame_right)
        self.frame_orders.setMinimumSize(QtCore.QSize(100, 250))
        self.frame_orders.setObjectName("frame_orders")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.frame_orders)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label_orders = QtWidgets.QLabel(self.frame_orders)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_orders.setFont(font)
        self.label_orders.setAlignment(QtCore.Qt.AlignCenter)
        self.label_orders.setObjectName("label_orders")
        self.vboxlayout1.addWidget(self.label_orders)
        self.value_orders = QtWidgets.QLabel(self.frame_orders)
        self.value_orders.setAlignment(QtCore.Qt.AlignCenter)
        self.value_orders.setObjectName("value_orders")
        self.vboxlayout1.addWidget(self.value_orders)
        self.hboxlayout.addWidget(self.frame_orders)
        self.frame_revenue = QtWidgets.QFrame(self.frame_right)
        self.frame_revenue.setObjectName("frame_revenue")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.frame_revenue)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label_revenue = QtWidgets.QLabel(self.frame_revenue)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_revenue.setFont(font)
        self.label_revenue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_revenue.setObjectName("label_revenue")
        self.vboxlayout2.addWidget(self.label_revenue)
        self.value_revenue = QtWidgets.QLabel(self.frame_revenue)
        self.value_revenue.setAlignment(QtCore.Qt.AlignCenter)
        self.value_revenue.setObjectName("value_revenue")
        self.vboxlayout2.addWidget(self.value_revenue)
        self.hboxlayout.addWidget(self.frame_revenue)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.table_stats = QtWidgets.QTableWidget(self.frame_right)
        self.table_stats.setObjectName("table_stats")
        self.table_stats.setColumnCount(3)
        self.table_stats.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_stats.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stats.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stats.setHorizontalHeaderItem(2, item)
        self.vboxlayout.addWidget(self.table_stats)
        self.horizontalLayout.addWidget(self.frame_right)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thống kê doanh thu"))
        self.btn_ban.setText(_translate("MainWindow", "Danh sách bàn"))
        self.btn_hd.setText(_translate("MainWindow", "Hóa đơn"))
        self.btn_tk.setText(_translate("MainWindow", "Thống kê"))
        self.btn_logout.setText(_translate("MainWindow", "Đăng xuất"))
        self.frame_orders.setStyleSheet(_translate("MainWindow", "background-color: #ffffff; border: 1px solid #ccc;"))
        self.label_orders.setText(_translate("MainWindow", "Đơn hàng"))
        self.value_orders.setStyleSheet(_translate("MainWindow", "font-size: 18px; font-weight: bold;"))
        self.value_orders.setText(_translate("MainWindow", "10"))
        self.frame_revenue.setStyleSheet(_translate("MainWindow", "background-color: #ffffff; border: 1px solid #ccc;"))
        self.label_revenue.setText(_translate("MainWindow", "Doanh thu"))
        self.value_revenue.setStyleSheet(_translate("MainWindow", "font-size: 18px; font-weight: bold;"))
        self.value_revenue.setText(_translate("MainWindow", "100.000 VND"))
        item = self.table_stats.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ngày"))
        item = self.table_stats.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Số đơn"))
        item = self.table_stats.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Doanh thu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
