# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1154)
        MainWindow.setStyleSheet("\n"
"    QMainWindow { background-color: #F8F5F2; }\n"
"    /* Nút món ăn */\n"
"    #menuGrid QPushButton { \n"
"        background-color: #FFFFFF; \n"
"        border: 1px solid #E0D7D0; \n"
"        border-radius: 12px; \n"
"        padding: 10px;\n"
"        min-width: 180px;\n"
"        min-height: 220px;\n"
"    }\n"
"    #menuGrid QPushButton:hover { background-color: #FDFCFB; border-color: #8C6A4B; }\n"
"    \n"
"    /* Bảng hóa đơn */\n"
"    QTableWidget { \n"
"        background-color: white; \n"
"        border: 1px solid #D7D2CB; \n"
"        border-radius: 8px; \n"
"        gridline-color: #F1EFEA;\n"
"        font-size: 13px;\n"
"    }\n"
"    QHeaderView::section { \n"
"        background-color: #8C6A4B; \n"
"        color: white; \n"
"        font-weight: bold; \n"
"        padding: 8px; \n"
"        border: none;\n"
"    }\n"
"    \n"
"    /* Nút chức năng */\n"
"    #btnExit { background-color: #E63946; color: white; font-weight: bold; border-radius: 8px; min-height: 45px; }\n"
"    #btnPayment { background-color: #588157; color: white; font-size: 18px; font-weight: bold; border-radius: 10px; min-height: 60px; border: none; }\n"
"    #btnPayment:hover { background-color: #3A5A40; }\n"
"QFrame#ProductCard {\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #E0E0E0;\n"
"}\n"
"\n"
"QFrame#ProductCard:hover {\n"
"    border: 2px solid #2D5A27;\n"
"    background-color: #FAFAFA;\n"
"}\n"
"\n"
"QLabel#PriceLabel {\n"
"    color: #2D5A27;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"/* Thiết lập nền cho toàn bộ cửa sổ */\n"
"QMainWindow {\n"
"    background-color: #FDF5E6; /* Màu nền phụ - Trắng kem */\n"
"}\n"
"\n"
"/* Kiểu dáng cho các ô sản phẩm (Widget) */\n"
".ProductCard {\n"
"    background-color: #603913; /* Màu nền chính - Nâu */\n"
"    border-radius: 10px;        /* Bo góc cho thân thiện */\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* Kiểu dáng cho tên sản phẩm */\n"
".ProductTitle {\n"
"    color: #FFFFFF;             /* Màu chữ chính - Trắng */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Kiểu dáng cho giá sản phẩm */\n"
".ProductPrice {\n"
"    color: #D9CAB3;             /* Màu chữ phụ - Kem nhạt */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột qua ô sản phẩm */\n"
".ProductCard:hover {\n"
"    background-color: #4F2F0F; /* Màu điểm nhấn - Nâu đậm hơn */\n"
"}\n"
"\n"
"/* Kiểu dáng cho nút thanh toán */\n"
"QPushButton#checkoutButton {\n"
"    background-color: #4CAF50; /* Hoặc #A0522D tùy chọn */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        self.mainLayout.setSpacing(25)
        self.mainLayout.setObjectName("mainLayout")
        self.leftCol = QtWidgets.QVBoxLayout()
        self.leftCol.setObjectName("leftCol")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setObjectName("btnExit")
        self.leftCol.addWidget(self.btnExit)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.leftCol.addItem(spacerItem)
        self.mainLayout.addLayout(self.leftCol)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 706, 1114))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setStyleSheet("QFrame {\n"
"    background-color: white; /* Màu nền ô */\n"
"    border: 1px solid #D7D2CB; /* Viền ô */\n"
"    border-radius: 12px; /* Bo góc tròn cho hiện đại */\n"
"    padding: 10px; /* Khoảng cách bên trong ô */\n"
"}\n"
"QFrame:hover {\n"
"    background-color: #fdfcfb; /* Màu nền khi di chuột vào */\n"
"    border: 2px solid #8c6a4b; /* Viền màu nâu đậm */\n"
"}")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1196, 1564))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bac_xiu = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bac_xiu.sizePolicy().hasHeightForWidth())
        self.bac_xiu.setSizePolicy(sizePolicy)
        self.bac_xiu.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.bac_xiu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bac_xiu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bac_xiu.setObjectName("bac_xiu")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.bac_xiu)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_9 = QtWidgets.QLabel(self.bac_xiu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(250, 300))
        self.label_9.setMaximumSize(QtCore.QSize(250, 300))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("D:/37010212-bac-xiu-2-105200.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.bac_xiu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_9.addWidget(self.pushButton_10, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.bac_xiu, 0, 2, 1, 1)
        self.capu = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capu.sizePolicy().hasHeightForWidth())
        self.capu.setSizePolicy(sizePolicy)
        self.capu.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.capu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.capu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.capu.setObjectName("capu")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.capu)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_13 = QtWidgets.QPushButton(self.capu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_11.addWidget(self.pushButton_13, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.capu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(250, 300))
        self.label_13.setMaximumSize(QtCore.QSize(250, 300))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("D:/how-to-make-cappuccinos-766116-hero-01-a754d567739b4ee0b209305138ecb996.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.capu, 1, 2, 1, 1)
        self.muoi = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.muoi.sizePolicy().hasHeightForWidth())
        self.muoi.setSizePolicy(sizePolicy)
        self.muoi.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.muoi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.muoi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.muoi.setObjectName("muoi")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.muoi)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_18 = QtWidgets.QLabel(self.muoi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(250, 300))
        self.label_18.setMaximumSize(QtCore.QSize(250, 300))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("D:/uong-ca-phe-muoi-nhieu-co-tot-khong.jpg"))
        self.label_18.setScaledContents(True)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.muoi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_6.addWidget(self.pushButton_18, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.muoi, 0, 3, 1, 1)
        self.latte = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.latte.sizePolicy().hasHeightForWidth())
        self.latte.setSizePolicy(sizePolicy)
        self.latte.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.latte.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.latte.setFrameShadow(QtWidgets.QFrame.Raised)
        self.latte.setObjectName("latte")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.latte)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_15 = QtWidgets.QLabel(self.latte)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(250, 300))
        self.label_15.setMaximumSize(QtCore.QSize(250, 300))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("D:/mon-latte-cafe.webp"))
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_12.addWidget(self.label_15, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.latte)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_12.addWidget(self.pushButton_15, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.latte, 1, 3, 1, 1)
        self.nau = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nau.sizePolicy().hasHeightForWidth())
        self.nau.setSizePolicy(sizePolicy)
        self.nau.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.nau.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.nau.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nau.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nau.setObjectName("nau")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.nau)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.nau)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(250, 300))
        self.label_3.setMaximumSize(QtCore.QSize(250, 300))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:/ca_phe_ae27c2fffbc4489884c2efbef3d639bb_grande.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.nau)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.nau, 0, 1, 1, 1)
        self.tratac = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tratac.sizePolicy().hasHeightForWidth())
        self.tratac.setSizePolicy(sizePolicy)
        self.tratac.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.tratac.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tratac.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tratac.setObjectName("tratac")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tratac)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.pushButton_20 = QtWidgets.QPushButton(self.tratac)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_20.addWidget(self.pushButton_20, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tratac)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(250, 300))
        self.label_20.setMaximumSize(QtCore.QSize(250, 300))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("D:/images (1).jpg"))
        self.label_20.setScaledContents(True)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_20.addWidget(self.label_20, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.tratac, 3, 1, 1, 1)
        self.ame = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ame.sizePolicy().hasHeightForWidth())
        self.ame.setSizePolicy(sizePolicy)
        self.ame.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.ame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ame.setObjectName("ame")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.ame)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_19 = QtWidgets.QLabel(self.ame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(250, 300))
        self.label_19.setMaximumSize(QtCore.QSize(250, 300))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("D:/2024_3_28_638472299342509511_avatar.webp"))
        self.label_19.setScaledContents(True)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_19.addWidget(self.label_19, 0, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.ame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_19.addWidget(self.pushButton_19, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.ame, 1, 1, 1, 1)
        self.caphcotdua = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caphcotdua.sizePolicy().hasHeightForWidth())
        self.caphcotdua.setSizePolicy(sizePolicy)
        self.caphcotdua.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.caphcotdua.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caphcotdua.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caphcotdua.setObjectName("caphcotdua")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.caphcotdua)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_17 = QtWidgets.QLabel(self.caphcotdua)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(250, 300))
        self.label_17.setMaximumSize(QtCore.QSize(250, 300))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("D:/ca-phe-cot-dua-thom-beo.jpg"))
        self.label_17.setScaledContents(True)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 0, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.caphcotdua)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_8.addWidget(self.pushButton_17, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.caphcotdua, 3, 3, 1, 1)
        self.tradaocamsa = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tradaocamsa.sizePolicy().hasHeightForWidth())
        self.tradaocamsa.setSizePolicy(sizePolicy)
        self.tradaocamsa.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.tradaocamsa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tradaocamsa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tradaocamsa.setObjectName("tradaocamsa")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tradaocamsa)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_14 = QtWidgets.QLabel(self.tradaocamsa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(250, 300))
        self.label_14.setMaximumSize(QtCore.QSize(250, 300))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("D:/tra-dao-cam-sa-ngot-ngao.webp"))
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_18.addWidget(self.label_14, 0, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.tradaocamsa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_18.addWidget(self.pushButton_14, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.tradaocamsa, 3, 2, 1, 1)
        self.espresso = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espresso.sizePolicy().hasHeightForWidth())
        self.espresso.setSizePolicy(sizePolicy)
        self.espresso.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.espresso.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espresso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espresso.setObjectName("espresso")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.espresso)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_16 = QtWidgets.QLabel(self.espresso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(250, 300))
        self.label_16.setMaximumSize(QtCore.QSize(250, 300))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("D:/espresso-coffee-recipe04-500x375.webp"))
        self.label_16.setScaledContents(True)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 0, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.espresso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_7.addWidget(self.pushButton_16, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.espresso, 1, 0, 1, 1)
        self.den = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.den.sizePolicy().hasHeightForWidth())
        self.den.setSizePolicy(sizePolicy)
        self.den.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.den.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.den.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.den.setFrameShadow(QtWidgets.QFrame.Raised)
        self.den.setObjectName("den")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.den)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.den)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.den)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(250, 300))
        self.label_2.setMaximumSize(QtCore.QSize(250, 300))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:/black-coffee-ca-phe-den-20231110205006_654e350e81642.webp"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.den, 0, 0, 1, 1)
        self.trachanh = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trachanh.sizePolicy().hasHeightForWidth())
        self.trachanh.setSizePolicy(sizePolicy)
        self.trachanh.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.trachanh.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trachanh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trachanh.setObjectName("trachanh")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.trachanh)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_11 = QtWidgets.QLabel(self.trachanh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(250, 300))
        self.label_11.setMaximumSize(QtCore.QSize(250, 300))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("D:/thum-1200x676-16.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.trachanh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_10.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.trachanh, 3, 0, 1, 1)
        self.caphcotdua_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caphcotdua_2.sizePolicy().hasHeightForWidth())
        self.caphcotdua_2.setSizePolicy(sizePolicy)
        self.caphcotdua_2.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.caphcotdua_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caphcotdua_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caphcotdua_2.setObjectName("caphcotdua_2")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.caphcotdua_2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.pushButton_21 = QtWidgets.QPushButton(self.caphcotdua_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_21.addWidget(self.pushButton_21, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.caphcotdua_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(250, 300))
        self.label_21.setMaximumSize(QtCore.QSize(250, 300))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("D:/nuoc-ep-cam-5235.jpg"))
        self.label_21.setScaledContents(True)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_21.addWidget(self.label_21, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.caphcotdua_2, 4, 2, 1, 1)
        self.caphcotdua_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caphcotdua_3.sizePolicy().hasHeightForWidth())
        self.caphcotdua_3.setSizePolicy(sizePolicy)
        self.caphcotdua_3.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.caphcotdua_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caphcotdua_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caphcotdua_3.setObjectName("caphcotdua_3")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.caphcotdua_3)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_22 = QtWidgets.QLabel(self.caphcotdua_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(250, 300))
        self.label_22.setMaximumSize(QtCore.QSize(250, 300))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("D:/images (2).jpg"))
        self.label_22.setScaledContents(True)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_22.addWidget(self.label_22, 0, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.caphcotdua_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_22.addWidget(self.pushButton_22, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.caphcotdua_3, 4, 3, 1, 1)
        self.caphcotdua_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caphcotdua_4.sizePolicy().hasHeightForWidth())
        self.caphcotdua_4.setSizePolicy(sizePolicy)
        self.caphcotdua_4.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.caphcotdua_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caphcotdua_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caphcotdua_4.setObjectName("caphcotdua_4")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.caphcotdua_4)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_23 = QtWidgets.QLabel(self.caphcotdua_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(250, 300))
        self.label_23.setMaximumSize(QtCore.QSize(250, 300))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("D:/cach-lam-nuoc-ep-dua-hau.webp"))
        self.label_23.setScaledContents(True)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_23.addWidget(self.label_23, 0, 0, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.caphcotdua_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_23.addWidget(self.pushButton_23, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.caphcotdua_4, 4, 1, 1, 1)
        self.caphcotdua_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caphcotdua_5.sizePolicy().hasHeightForWidth())
        self.caphcotdua_5.setSizePolicy(sizePolicy)
        self.caphcotdua_5.setStyleSheet("QLabel {\n"
"    /* Đảm bảo ảnh không bị lặp lại */\n"
"    background-repeat: no-repeat;\n"
"    /* Căn giữa ảnh cả chiều dọc và ngang */\n"
"    background-position: center;\n"
"    /* Co giãn ảnh vừa với khung nhưng vẫn giữ tỷ lệ, không bị méo */\n"
"    background-size: contain;\n"
"}")
        self.caphcotdua_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caphcotdua_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caphcotdua_5.setObjectName("caphcotdua_5")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.caphcotdua_5)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_24 = QtWidgets.QLabel(self.caphcotdua_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(250, 300))
        self.label_24.setMaximumSize(QtCore.QSize(250, 300))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("D:/Dua-Tuoi.webp"))
        self.label_24.setScaledContents(True)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_24.addWidget(self.label_24, 0, 0, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.caphcotdua_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_24.addWidget(self.pushButton_24, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.caphcotdua_5, 4, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_3, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainLayout.addWidget(self.scrollArea)
        self.rightCol = QtWidgets.QVBoxLayout()
        self.rightCol.setObjectName("rightCol")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.rightCol.addWidget(self.tableWidget)
        self.lblTotal = QtWidgets.QLabel(self.centralwidget)
        self.lblTotal.setStyleSheet("font-size: 22px; font-weight: bold; color: #4A3C31; padding: 10px 0;")
        self.lblTotal.setAlignment(QtCore.Qt.AlignVCenter)
        self.lblTotal.setObjectName("lblTotal")
        self.rightCol.addWidget(self.lblTotal)
        self.btnPayment = QtWidgets.QPushButton(self.centralwidget)
        self.btnPayment.setObjectName("btnPayment")
        self.rightCol.addWidget(self.btnPayment)
        self.mainLayout.addLayout(self.rightCol)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 7)
        self.mainLayout.setStretch(2, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coffee Management System"))
        self.btnExit.setText(_translate("MainWindow", "Danh sách bàn"))
        self.pushButton_10.setText(_translate("MainWindow", "Bạc xỉu\n"
"35.000"))
        self.pushButton_13.setText(_translate("MainWindow", "Cappuchino\n"
"45.000"))
        self.pushButton_18.setText(_translate("MainWindow", "Cà phê muối\n"
"35.000"))
        self.pushButton_15.setText(_translate("MainWindow", "Latte\n"
"45.000"))
        self.pushButton_3.setText(_translate("MainWindow", "Nâu đá\n"
"25.000"))
        self.pushButton_20.setText(_translate("MainWindow", "Trà tắc\n"
"30.000"))
        self.pushButton_19.setText(_translate("MainWindow", "Americano\n"
"40.000"))
        self.pushButton_17.setText(_translate("MainWindow", "Cà phê cốt dừa\n"
"35.000"))
        self.pushButton_14.setText(_translate("MainWindow", "Trà đào cam xả\n"
"40.000"))
        self.pushButton_16.setText(_translate("MainWindow", "Espresso\n"
"40.000"))
        self.pushButton_2.setText(_translate("MainWindow", "Đen đá\n"
"25.000"))
        self.pushButton_9.setText(_translate("MainWindow", "Trà chanh\n"
"30.000"))
        self.pushButton_21.setText(_translate("MainWindow", "Nước ép cam\n"
"35.000"))
        self.pushButton_22.setText(_translate("MainWindow", "Matcha latte\n"
"45.000"))
        self.pushButton_23.setText(_translate("MainWindow", "Nước ép dưa hấu\n"
"35.000"))
        self.pushButton_24.setText(_translate("MainWindow", "Dừa tươi\n"
"40.000"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Món"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SL"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Giá"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tổng"))
        self.lblTotal.setText(_translate("MainWindow", "TỔNG CỘNG: 0 VNĐ"))
        self.btnPayment.setText(_translate("MainWindow", "XÁC NHẬN THANH TOÁN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
