import os
from PyQt5 import QtCore, QtGui, QtWidgets, uic

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(CURRENT_DIR)
class DSWindow(QtWidgets.QMainWindow):
    def __init__(self, parent_widget):
        super().__init__()
        self.widget = parent_widget
        # Load file UI tương ứng (ví dụ danhsachban.ui)
        uic.loadUi(os.path.join(BASE_DIR, 'view', 'danhsachban.ui'), self)
        
        # Kết nối các nút bấm trên màn hình danh sách bàn
        # self.btn_back.clicked.connect(self.go_back)
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 1546)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: #5a2d0c;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7a3f14;\n"
"}\n"
"QFrame#sidebar {\n"
"    background-color: #e8d3b3;\n"
"}\n"
"QFrame#main_area {\n"
"    background-color: #f5e6cc;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(self.sidebar)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("D:/16edaf03-df12-4f77-90d0-a4496ceb8155.jpg"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.btn_ban_2 = QtWidgets.QPushButton(self.sidebar)
        self.btn_ban_2.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_ban_2.setFont(font)
        self.btn_ban_2.setObjectName("btn_ban_2")
        self.verticalLayout.addWidget(self.btn_ban_2)
        self.btn_ban = QtWidgets.QPushButton(self.sidebar)
        self.btn_ban.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_ban.setFont(font)
        self.btn_ban.setObjectName("btn_ban")
        self.verticalLayout.addWidget(self.btn_ban)
        self.btn_tk = QtWidgets.QPushButton(self.sidebar)
        self.btn_tk.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_tk.setFont(font)
        self.btn_tk.setObjectName("btn_tk")
        self.verticalLayout.addWidget(self.btn_tk)
        self.btn_logout = QtWidgets.QPushButton(self.sidebar)
        self.btn_logout.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout.addWidget(self.btn_logout)
        self.horizontalLayout.addWidget(self.sidebar)
        self.main_area = QtWidgets.QFrame(self.centralwidget)
        self.main_area.setObjectName("main_area")
        self.gridLayout = QtWidgets.QGridLayout(self.main_area)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.main_area)
        self.frame.setMinimumSize(QtCore.QSize(20, 15))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.table_frame = QtWidgets.QFrame(self.main_area)
        self.table_frame.setObjectName("table_frame")
        self.gridlayout = QtWidgets.QGridLayout(self.table_frame)
        self.gridlayout.setObjectName("gridlayout")
        self.btn_10 = QtWidgets.QPushButton(self.table_frame)
        self.btn_10.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_10.setFont(font)
        self.btn_10.setObjectName("btn_10")
        self.gridlayout.addWidget(self.btn_10, 3, 1, 1, 1)
        self.btn_01 = QtWidgets.QPushButton(self.table_frame)
        self.btn_01.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_01.setFont(font)
        self.btn_01.setObjectName("btn_01")
        self.gridlayout.addWidget(self.btn_01, 0, 1, 1, 1)
        self.btn_03 = QtWidgets.QPushButton(self.table_frame)
        self.btn_03.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_03.setFont(font)
        self.btn_03.setObjectName("btn_03")
        self.gridlayout.addWidget(self.btn_03, 1, 0, 1, 1)
        self.btn_07 = QtWidgets.QPushButton(self.table_frame)
        self.btn_07.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_07.setFont(font)
        self.btn_07.setObjectName("btn_07")
        self.gridlayout.addWidget(self.btn_07, 2, 1, 1, 1)
        self.btn_08 = QtWidgets.QPushButton(self.table_frame)
        self.btn_08.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_08.setFont(font)
        self.btn_08.setObjectName("btn_08")
        self.gridlayout.addWidget(self.btn_08, 2, 2, 1, 1)
        self.btn_05 = QtWidgets.QPushButton(self.table_frame)
        self.btn_05.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_05.setFont(font)
        self.btn_05.setObjectName("btn_05")
        self.gridlayout.addWidget(self.btn_05, 1, 2, 1, 1)
        self.btn_06 = QtWidgets.QPushButton(self.table_frame)
        self.btn_06.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_06.setFont(font)
        self.btn_06.setObjectName("btn_06")
        self.gridlayout.addWidget(self.btn_06, 2, 0, 1, 1)
        self.btn_takeaway = QtWidgets.QPushButton(self.table_frame)
        self.btn_takeaway.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_takeaway.setFont(font)
        self.btn_takeaway.setObjectName("btn_takeaway")
        self.gridlayout.addWidget(self.btn_takeaway, 0, 0, 1, 1)
        self.btn_02 = QtWidgets.QPushButton(self.table_frame)
        self.btn_02.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_02.setFont(font)
        self.btn_02.setObjectName("btn_02")
        self.gridlayout.addWidget(self.btn_02, 0, 2, 1, 1)
        self.btn_04 = QtWidgets.QPushButton(self.table_frame)
        self.btn_04.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_04.setFont(font)
        self.btn_04.setObjectName("btn_04")
        self.gridlayout.addWidget(self.btn_04, 1, 1, 1, 1)
        self.btn_09 = QtWidgets.QPushButton(self.table_frame)
        self.btn_09.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_09.setFont(font)
        self.btn_09.setObjectName("btn_09")
        self.gridlayout.addWidget(self.btn_09, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.table_frame, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.main_area)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quản lý bán"))
        self.btn_ban_2.setText(_translate("MainWindow", "Danh sách bàn"))
        self.btn_ban.setText(_translate("MainWindow", "Hóa đơn"))
        self.btn_tk.setText(_translate("MainWindow", "Thống kê"))
        self.btn_logout.setText(_translate("MainWindow", "Menu"))
        self.label_2.setText(_translate("MainWindow", "Đang dùng: 0/10"))
        self.btn_10.setText(_translate("MainWindow", "10"))
        self.btn_01.setText(_translate("MainWindow", "01"))
        self.btn_03.setText(_translate("MainWindow", "03"))
        self.btn_07.setText(_translate("MainWindow", "07"))
        self.btn_08.setText(_translate("MainWindow", "08"))
        self.btn_05.setText(_translate("MainWindow", "05"))
        self.btn_06.setText(_translate("MainWindow", "06"))
        self.btn_takeaway.setText(_translate("MainWindow", "Mang về"))
        self.btn_02.setText(_translate("MainWindow", "02"))
        self.btn_04.setText(_translate("MainWindow", "04"))
        self.btn_09.setText(_translate("MainWindow", "09"))

class DSWindow(QtWidgets.QMainWindow):
    def __init__(self, parent_widget):
        super().__init__()
        self.widget = parent_widget
        # Load file UI tương ứng (ví dụ danhsachban.ui)
        uic.loadUi(os.path.join(BASE_DIR, 'view', 'danhsachban.ui'), self)
        
        # Kết nối các nút bấm trên màn hình danh sách bàn
        # self.btn_back.clicked.connect(self.go_back)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
