# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(1130, 1383)
        Menu.setStyleSheet("QPushButton {\n"
"    background-color: #5a2d0c;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7a3f14;\n"
"}\n"
"QFrame#sidebar {\n"
"    background-color: #e8d3b3;\n"
"}\n"
"QFrame#main_area {\n"
"    background-color: #f5e6cc;\n"
"}\n"
"/* Tổng thể cửa sổ */\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"\n"
"/* TabBar - Thanh menu danh mục (Cà phê, Trà...) */\n"
"QTabBar::tab {\n"
"    background: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    padding: 10px 20px;\n"
"    margin-right: 2px;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    color: #5d4037;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #6f4e37; /* Màu cà phê */\n"
"    color: white;\n"
"    border-bottom-color: #6f4e37;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #efebe9;\n"
"}\n"
"\n"
"/* Card sản phẩm (Dựa trên QFrame hoặc QWidget chứa ảnh/tên) */\n"
"/* Giả sử mỗi item là một QFrame */\n"
"#productCard {\n"
"    background-color: white;\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"#productCard:hover {\n"
"    border: 2px solid #6f4e37;\n"
"    background-color: #fafafa;\n"
"}\n"
"\n"
"/* Nhãn tên sản phẩm và giá */\n"
"QLabel {\n"
"    color: #3e2723;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"}\n"
"\n"
"#priceLabel {\n"
"    color: #8d6e63;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Khu vực hóa đơn (Bên phải) */\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    gridline-color: #f0f0f0;\n"
"    selection-background-color: #d7ccc8;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #6f4e37;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Nút Thanh Toán */\n"
"QPushButton#payButton {\n"
"    background-color: #6f4e37;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#payButton:hover {\n"
"    background-color: #5d4037;\n"
"}\n"
"\n"
"QPushButton#payButton:pressed {\n"
"    background-color: #3e2723;\n"
"}\n"
"\n"
"/* Tổng cộng */\n"
"#totalLabel {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #d32f2f; /* Màu đỏ nổi bật cho tiền */\n"
"}\n"
"/* Tăng kích thước các tab */\n"
"QTabBar::tab {\n"
"    background: #f8f9fa;\n"
"    border: 1px solid #d1d1d1;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    \n"
"    /* Chỉnh kích thước ở đây */\n"
"    min-width: 130px;  /* Độ dài tối thiểu của mỗi tab */\n"
"    min-height: 40px;  /* Chiều cao của tab */\n"
"    padding: 5px 20px; /* Khoảng cách chữ bên trong */\n"
"    font-size: 14px;   /* Cỡ chữ to hơn */\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"/* Màu sắc khi tab được chọn */\n"
"QTabBar::tab:selected {\n"
"    background-color: #6f4e37; /* Màu nâu cà phê */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: 1px solid #6f4e37;\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột qua tab */\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"/* Giả sử Object Name của nút là btn_pay hoặc tương tự */\n"
"/* Bạn có thể thay đổi tên ID sau dấu # cho đúng với tên bạn đặt trong Qt Designer */\n"
"\n"
"QPushButton#btn_pay {\n"
"    background-color: #26a69a; /* Màu xanh Teal hiện đại */\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 12px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#btn_pay:hover {\n"
"    background-color: #2bbbad; /* Sáng hơn khi di chuột */\n"
"}\n"
"\n"
"QPushButton#btn_pay:pressed {\n"
"    background-color: #00695c; /* Đậm hơn khi click */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = QtWidgets.QLabel(self.sidebar)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("D:/16edaf03-df12-4f77-90d0-a4496ceb8155.jpg"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.logo)
        self.btn_ban_2 = QtWidgets.QPushButton(self.sidebar)
        self.btn_ban_2.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_ban_2.setFont(font)
        self.btn_ban_2.setObjectName("btn_ban_2")
        self.verticalLayout_2.addWidget(self.btn_ban_2)
        self.btn_ban = QtWidgets.QPushButton(self.sidebar)
        self.btn_ban.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_ban.setFont(font)
        self.btn_ban.setObjectName("btn_ban")
        self.verticalLayout_2.addWidget(self.btn_ban)
        self.btn_tk = QtWidgets.QPushButton(self.sidebar)
        self.btn_tk.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_tk.setFont(font)
        self.btn_tk.setObjectName("btn_tk")
        self.verticalLayout_2.addWidget(self.btn_tk)
        self.btn_logout = QtWidgets.QPushButton(self.sidebar)
        self.btn_logout.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_2.addWidget(self.btn_logout)
        self.horizontalLayout_6.addWidget(self.sidebar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.topbar = QtWidgets.QHBoxLayout()
        self.topbar.setObjectName("topbar")
        self.label_menu = QtWidgets.QLabel(self.centralwidget)
        self.label_menu.setStyleSheet("font-size:24px; font-weight:bold;")
        self.label_menu.setObjectName("label_menu")
        self.topbar.addWidget(self.label_menu)
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setMaximumSize(QtCore.QSize(16777215, 50))
        self.search.setObjectName("search")
        self.topbar.addWidget(self.search)
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setMaximumSize(QtCore.QSize(500, 50))
        self.btn_add.setStyleSheet("background:#F4A261; font-size:18px;")
        self.btn_add.setObjectName("btn_add")
        self.topbar.addWidget(self.btn_add)
        self.topbar.setStretch(0, 5)
        self.topbar.setStretch(1, 10)
        self.topbar.setStretch(2, 2)
        self.verticalLayout.addLayout(self.topbar)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("/* Chỉnh font chữ cho tiêu đề Tab */\n"
"QTabBar::tab {\n"
"    font-size: 18px;          /* Tăng kích cỡ chữ lên 18px */\n"
"    font-weight: bold;        /* Làm đậm chữ */\n"
"    height: 50px;             /* Chỉnh chiều cao của thanh Tab */\n"
"    width: 200px;             /* Chỉnh độ rộng cố định để các tab bằng nhau */\n"
"    min-width: 150px;         /* Đảm bảo độ rộng tối thiểu */\n"
"}\n"
"\n"
"/* Hiệu ứng khi chọn vào Tab (để giữ màu nâu bạn đang có) */\n"
"QTabBar::tab:selected {\n"
"    background: #7d5a44;      /* Màu nâu giống trong hình của bạn */\n"
"    color: white;             /* Màu chữ khi chọn */\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("\n"
"    QMainWindow { background-color: #F8F5F2; }\n"
"    /* Nút món ăn */\n"
"    #menuGrid QPushButton { \n"
"        background-color: #FFFFFF; \n"
"        border: 1px solid #E0D7D0; \n"
"        border-radius: 12px; \n"
"        padding: 10px;\n"
"        min-width: 180px;\n"
"        min-height: 220px;\n"
"    }\n"
"    #menuGrid QPushButton:hover { background-color: #FDFCFB; border-color: #8C6A4B; }\n"
"    \n"
"    /* Bảng hóa đơn */\n"
"    QTableWidget { \n"
"        background-color: white; \n"
"        border: 1px solid #D7D2CB; \n"
"        border-radius: 8px; \n"
"        gridline-color: #F1EFEA;\n"
"        font-size: 13px;\n"
"    }\n"
"    QHeaderView::section { \n"
"        background-color: #8C6A4B; \n"
"        color: white; \n"
"        font-weight: bold; \n"
"        padding: 8px; \n"
"        border: none;\n"
"    }\n"
"    \n"
"    /* Nút chức năng */\n"
"    #btnExit { background-color: #E63946; color: white; font-weight: bold; border-radius: 8px; min-height: 45px; }\n"
"    #btnPayment { background-color: #588157; color: white; font-size: 18px; font-weight: bold; border-radius: 10px; min-height: 60px; border: none; }\n"
"    #btnPayment:hover { background-color: #3A5A40; }\n"
"QFrame#ProductCard {\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #E0E0E0;\n"
"}\n"
"\n"
"QFrame#ProductCard:hover {\n"
"    border: 2px solid #2D5A27;\n"
"    background-color: #FAFAFA;\n"
"}\n"
"\n"
"QLabel#PriceLabel {\n"
"    color: #2D5A27;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"/* Thiết lập nền cho toàn bộ cửa sổ */\n"
"QMainWindow {\n"
"    background-color: #FDF5E6; /* Màu nền phụ - Trắng kem */\n"
"}\n"
"\n"
"/* Kiểu dáng cho các ô sản phẩm (Widget) */\n"
".ProductCard {\n"
"    background-color: #603913; /* Màu nền chính - Nâu */\n"
"    border-radius: 10px;        /* Bo góc cho thân thiện */\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* Kiểu dáng cho tên sản phẩm */\n"
".ProductTitle {\n"
"    color: #FFFFFF;             /* Màu chữ chính - Trắng */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Kiểu dáng cho giá sản phẩm */\n"
".ProductPrice {\n"
"    color: #D9CAB3;             /* Màu chữ phụ - Kem nhạt */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột qua ô sản phẩm */\n"
".ProductCard:hover {\n"
"    background-color: #4F2F0F; /* Màu điểm nhấn - Nâu đậm hơn */\n"
"}\n"
"\n"
"/* Kiểu dáng cho nút thanh toán */\n"
"QPushButton#checkoutButton {\n"
"    background-color: #4CAF50; /* Hoặc #A0522D tùy chọn */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"}\n"
"   ")
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 580, 1117))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.product_list_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.product_list_5.setObjectName("product_list_5")
        self._6 = QtWidgets.QHBoxLayout()
        self._6.setObjectName("_6")
        self.img1_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.img1_5.setObjectName("img1_5")
        self._6.addWidget(self.img1_5)
        self.name1_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.name1_5.setObjectName("name1_5")
        self._6.addWidget(self.name1_5)
        self.price1_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.price1_5.setObjectName("price1_5")
        self._6.addWidget(self.price1_5)
        self.edit1_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.edit1_5.setObjectName("edit1_5")
        self._6.addWidget(self.edit1_5)
        self.del1_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.del1_5.setObjectName("del1_5")
        self._6.addWidget(self.del1_5)
        self.product_list_5.addLayout(self._6)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_5.addWidget(self.scrollArea_5)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 580, 1117))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.product_list_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.product_list_2.setObjectName("product_list_2")
        self._3 = QtWidgets.QHBoxLayout()
        self._3.setObjectName("_3")
        self.img1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.img1_2.setObjectName("img1_2")
        self._3.addWidget(self.img1_2)
        self.name1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.name1_2.setObjectName("name1_2")
        self._3.addWidget(self.name1_2)
        self.price1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.price1_2.setObjectName("price1_2")
        self._3.addWidget(self.price1_2)
        self.edit1_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.edit1_2.setObjectName("edit1_2")
        self._3.addWidget(self.edit1_2)
        self.del1_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.del1_2.setObjectName("del1_2")
        self._3.addWidget(self.del1_2)
        self.product_list_2.addLayout(self._3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 580, 1117))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.product_list = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.product_list.setObjectName("product_list")
        self._2 = QtWidgets.QHBoxLayout()
        self._2.setObjectName("_2")
        self.img1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img1.setObjectName("img1")
        self._2.addWidget(self.img1)
        self.name1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.name1.setObjectName("name1")
        self._2.addWidget(self.name1)
        self.price1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.price1.setObjectName("price1")
        self._2.addWidget(self.price1)
        self.edit1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.edit1.setObjectName("edit1")
        self._2.addWidget(self.edit1)
        self.del1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.del1.setObjectName("del1")
        self._2.addWidget(self.del1)
        self.product_list.addLayout(self._2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 580, 1117))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.product_list_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.product_list_3.setObjectName("product_list_3")
        self._4 = QtWidgets.QHBoxLayout()
        self._4.setObjectName("_4")
        self.img1_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.img1_3.setObjectName("img1_3")
        self._4.addWidget(self.img1_3)
        self.name1_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.name1_3.setObjectName("name1_3")
        self._4.addWidget(self.name1_3)
        self.price1_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.price1_3.setObjectName("price1_3")
        self._4.addWidget(self.price1_3)
        self.edit1_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.edit1_3.setObjectName("edit1_3")
        self._4.addWidget(self.edit1_3)
        self.del1_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.del1_3.setObjectName("del1_3")
        self._4.addWidget(self.del1_3)
        self.product_list_3.addLayout(self._4)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_2.addWidget(self.scrollArea_4)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 580, 1117))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.product_list_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.product_list_4.setObjectName("product_list_4")
        self._5 = QtWidgets.QHBoxLayout()
        self._5.setObjectName("_5")
        self.img1_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.img1_4.setObjectName("img1_4")
        self._5.addWidget(self.img1_4)
        self.name1_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.name1_4.setObjectName("name1_4")
        self._5.addWidget(self.name1_4)
        self.price1_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.price1_4.setObjectName("price1_4")
        self._5.addWidget(self.price1_4)
        self.edit1_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.edit1_4.setObjectName("edit1_4")
        self._5.addWidget(self.edit1_4)
        self.del1_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.del1_4.setObjectName("del1_4")
        self._5.addWidget(self.del1_4)
        self.product_list_4.addLayout(self._5)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 11)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 22))
        self.menubar.setObjectName("menubar")
        Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu)
        self.statusbar.setObjectName("statusbar")
        Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Menu)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "MainWindow"))
        self.btn_ban_2.setText(_translate("Menu", "Danh sách bàn"))
        self.btn_ban.setText(_translate("Menu", "Hóa đơn"))
        self.btn_tk.setText(_translate("Menu", "Thống kê"))
        self.btn_logout.setText(_translate("Menu", "Menu"))
        self.label_menu.setText(_translate("Menu", "Menu"))
        self.search.setPlaceholderText(_translate("Menu", "Tìm kiếm..."))
        self.btn_add.setText(_translate("Menu", "+"))
        self.img1_5.setText(_translate("Menu", "[IMG]"))
        self.name1_5.setText(_translate("Menu", "Đen đá"))
        self.price1_5.setText(_translate("Menu", "35.000 VND"))
        self.edit1_5.setText(_translate("Menu", "Sửa"))
        self.del1_5.setText(_translate("Menu", "X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Menu", "Cà phê"))
        self.img1_2.setText(_translate("Menu", "[IMG]"))
        self.name1_2.setText(_translate("Menu", "Trà chanh"))
        self.price1_2.setText(_translate("Menu", "35.000 VND"))
        self.edit1_2.setText(_translate("Menu", "Sửa"))
        self.del1_2.setText(_translate("Menu", "X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Menu", "Trà"))
        self.img1.setText(_translate("Menu", "[IMG]"))
        self.name1.setText(_translate("Menu", "Sinh tố bơ"))
        self.price1.setText(_translate("Menu", "35.000 VND"))
        self.edit1.setText(_translate("Menu", "Sửa"))
        self.del1.setText(_translate("Menu", "X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Menu", "Nước ép - Sinh tố"))
        self.img1_3.setText(_translate("Menu", "[IMG]"))
        self.name1_3.setText(_translate("Menu", "Sữa chua đánh đá"))
        self.price1_3.setText(_translate("Menu", "35.000 VND"))
        self.edit1_3.setText(_translate("Menu", "Sửa"))
        self.del1_3.setText(_translate("Menu", "X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Menu", "Đá xay - Sữa chua"))
        self.img1_4.setText(_translate("Menu", "[IMG]"))
        self.name1_4.setText(_translate("Menu", "Cacao"))
        self.price1_4.setText(_translate("Menu", "35.000 VND"))
        self.edit1_4.setText(_translate("Menu", "Sửa"))
        self.del1_4.setText(_translate("Menu", "X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Menu", "Cacao - Matcha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QMainWindow()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
