# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'themmon.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProductWindow(object):
    def setupUi(self, AddProductWindow):
        AddProductWindow.setObjectName("AddProductWindow")
        AddProductWindow.resize(900, 600)
        AddProductWindow.setStyleSheet("QPushButton {\n"
"    background-color: #5D2E0E; /* Màu nâu */\n"
"    color: white;              /* Chữ trắng */\n"
"    border-radius: 10px;       /* Bo góc */\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #4A250B; /* Đổi màu khi di chuột vào */\n"
"}\n"
"#centralwidget {\n"
"    background-color: #F5EBD7; \n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(AddProductWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formFrame = QtWidgets.QFrame(self.centralwidget)
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QVBoxLayout(self.formFrame)
        self.formLayout.setObjectName("formLayout")
        self.title = QtWidgets.QLabel(self.formFrame)
        self.title.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.formLayout.addWidget(self.title)
        self.tenSanPham = QtWidgets.QLineEdit(self.formFrame)
        self.tenSanPham.setMinimumSize(QtCore.QSize(0, 30))
        self.tenSanPham.setObjectName("tenSanPham")
        self.formLayout.addWidget(self.tenSanPham)
        self.loaiSanPham = QtWidgets.QComboBox(self.formFrame)
        self.loaiSanPham.setMinimumSize(QtCore.QSize(0, 30))
        self.loaiSanPham.setObjectName("loaiSanPham")
        self.loaiSanPham.addItem("")
        self.loaiSanPham.addItem("")
        self.loaiSanPham.addItem("")
        self.loaiSanPham.addItem("")
        self.loaiSanPham.addItem("")
        self.formLayout.addWidget(self.loaiSanPham)
        self.giaBan = QtWidgets.QLineEdit(self.formFrame)
        self.giaBan.setMinimumSize(QtCore.QSize(0, 30))
        self.giaBan.setObjectName("giaBan")
        self.formLayout.addWidget(self.giaBan)
        self.btnThemAnh_2 = QtWidgets.QPushButton(self.formFrame)
        self.btnThemAnh_2.setObjectName("btnThemAnh_2")
        self.formLayout.addWidget(self.btnThemAnh_2)
        self.horizontalLayout.addWidget(self.formFrame)
        self.imageFrame = QtWidgets.QFrame(self.centralwidget)
        self.imageFrame.setObjectName("imageFrame")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.imageFrame)
        self.vboxlayout.setObjectName("vboxlayout")
        self.btnThemAnh = QtWidgets.QPushButton(self.imageFrame)
        self.btnThemAnh.setObjectName("btnThemAnh")
        self.vboxlayout.addWidget(self.btnThemAnh)
        self.preview = QtWidgets.QLabel(self.imageFrame)
        self.preview.setMinimumSize(QtCore.QSize(150, 150))
        self.preview.setAlignment(QtCore.Qt.AlignCenter)
        self.preview.setObjectName("preview")
        self.vboxlayout.addWidget(self.preview)
        self.horizontalLayout.addWidget(self.imageFrame)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        AddProductWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddProductWindow)
        QtCore.QMetaObject.connectSlotsByName(AddProductWindow)

    def retranslateUi(self, AddProductWindow):
        _translate = QtCore.QCoreApplication.translate
        AddProductWindow.setWindowTitle(_translate("AddProductWindow", "Thêm sản phẩm"))
        self.title.setText(_translate("AddProductWindow", "THÊM SẢN PHẨM MỚI VÀO MENU"))
        self.tenSanPham.setPlaceholderText(_translate("AddProductWindow", "TÊN SẢN PHẨM"))
        self.loaiSanPham.setItemText(0, _translate("AddProductWindow", "Cà phê"))
        self.loaiSanPham.setItemText(1, _translate("AddProductWindow", "Đá xay - Sữa chua"))
        self.loaiSanPham.setItemText(2, _translate("AddProductWindow", "Trà"))
        self.loaiSanPham.setItemText(3, _translate("AddProductWindow", "Cacao - Matcha"))
        self.loaiSanPham.setItemText(4, _translate("AddProductWindow", "Sinh tố - Nước ép"))
        self.giaBan.setPlaceholderText(_translate("AddProductWindow", "GIÁ BÁN"))
        self.btnThemAnh_2.setText(_translate("AddProductWindow", "Thêm món"))
        self.btnThemAnh.setText(_translate("AddProductWindow", "Thêm ảnh"))
        self.preview.setText(_translate("AddProductWindow", "Preview"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddProductWindow = QtWidgets.QMainWindow()
    ui = Ui_AddProductWindow()
    ui.setupUi(AddProductWindow)
    AddProductWindow.show()
    sys.exit(app.exec_())
