# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thongke.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RevenueWindow(object):
    def setupUi(self, RevenueWindow):
        RevenueWindow.setObjectName("RevenueWindow")
        RevenueWindow.resize(745, 1434)
        RevenueWindow.setStyleSheet("QPushButton {\n"
"    background-color: #5a2d0c;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7a3f14;\n"
"}\n"
"QFrame#sidebar {\n"
"    background-color: #e8d3b3;\n"
"}\n"
"QFrame#main_area {\n"
"    background-color: #f5e6cc;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(RevenueWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = QtWidgets.QLabel(self.sidebar)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("D:/16edaf03-df12-4f77-90d0-a4496ceb8155.jpg"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.logo)
        self.btn_ban_2 = QtWidgets.QPushButton(self.sidebar)
        self.btn_ban_2.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_ban_2.setFont(font)
        self.btn_ban_2.setObjectName("btn_ban_2")
        self.verticalLayout_2.addWidget(self.btn_ban_2)
        self.btn_ban = QtWidgets.QPushButton(self.sidebar)
        self.btn_ban.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_ban.setFont(font)
        self.btn_ban.setObjectName("btn_ban")
        self.verticalLayout_2.addWidget(self.btn_ban)
        self.btn_tk = QtWidgets.QPushButton(self.sidebar)
        self.btn_tk.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_tk.setFont(font)
        self.btn_tk.setObjectName("btn_tk")
        self.verticalLayout_2.addWidget(self.btn_tk)
        self.btn_logout = QtWidgets.QPushButton(self.sidebar)
        self.btn_logout.setMinimumSize(QtCore.QSize(100, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_2.addWidget(self.btn_logout)
        self.horizontalLayout.addWidget(self.sidebar)
        self.chartTitle = QtWidgets.QLabel(self.centralwidget)
        self.chartTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.chartTitle.setObjectName("chartTitle")
        self.horizontalLayout.addWidget(self.chartTitle)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        RevenueWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RevenueWindow)
        QtCore.QMetaObject.connectSlotsByName(RevenueWindow)

    def retranslateUi(self, RevenueWindow):
        _translate = QtCore.QCoreApplication.translate
        RevenueWindow.setWindowTitle(_translate("RevenueWindow", "Thống kê doanh thu"))
        self.btn_ban_2.setText(_translate("RevenueWindow", "Danh sách bàn"))
        self.btn_ban.setText(_translate("RevenueWindow", "Hóa đơn"))
        self.btn_tk.setText(_translate("RevenueWindow", "Thống kê"))
        self.btn_logout.setText(_translate("RevenueWindow", "Menu"))
        self.chartTitle.setText(_translate("RevenueWindow", "Biểu đồ doanh thu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RevenueWindow = QtWidgets.QMainWindow()
    ui = Ui_RevenueWindow()
    ui.setupUi(RevenueWindow)
    RevenueWindow.show()
    sys.exit(app.exec_())
